### ISSUE TITLE
Fetch hole-ice kernel code from 2018

### ISSUE THREAD

**Issue by fiedl** [fiedl/hole-ice-scripts#12]
I'm trying to get the hole-ice code from 2018 working with current icetray.

The hole-ice code from 2018 consists of:

- [x] kernel code ➝ https://github.com/fiedl/hole-ice-scripts/issues/12
- [x] clsim code to pass parameters to the kernel ➝ https://github.com/fiedl/hole-ice-scripts/issues/15
- [ ] clsim additions for direct detection
- [ ] clsim additions for memory management
- [ ] steamshovel patches and artists
- [ ] example scripts

As a first step, fetch the kernel code from 2018 and try to apply it to current clsim.

## Where is the previous code?

The clsim hole-ice code used in the 2018 thesis [**The Effect of Hole Ice on the Propagation and Detection of Light in IceCube**](https://arxiv.org/abs/1904.08422) ([arxiv](https://arxiv.org/abs/1904.08422) | [pdf](https://github.com/fiedl/hole-ice-latex/releases/download/v1.0/diplomarbeit.pdf) | [latex](https://github.com/fiedl/hole-ice-latex) | [github](https://github.com/fiedl/hole-ice-study)) can be found in this fork of clsim: https://github.com/fiedl/clsim

To have a look at the `git diff` between the standard clsim of that time and the hole-ice clsim, open the diff on github:

https://github.com/fiedl/clsim/compare/3703cb2aa42c831623bc6763bf631cbdebf7d0a2...fiedl:clsim:sf/hole-ice-2018?w=1

Or show that diff locally:

```
[2022-09-10 15:17:33] fiedl@fiedl-mbp ~/icecube
▶ git clone git@github.com:fiedl/clsim.git

[2022-09-10 15:17:33] fiedl@fiedl-mbp ~/icecube/clsim sf/hole-ice-2018 32215a5
▶ git diff --ignore-all-space 3703cb2a..sf/hole-ice-2018
```

**Comment by fiedl** [comment]
- [x] Fetch kernel libraries from https://github.com/fiedl/clsim/tree/sf/hole-ice-2018/resources/kernels/lib
- [x] `#include` them in the `propagation_kernel.c.cl`
- [x] Run without configuration
- [x] [Add hard-coded dummy configuration and run](https://github.com/fiedl/hole-ice-scripts/issues/12#issuecomment-1242806580)

**Comment by fiedl** [comment]
```
[2022-09-09 22:21:39] fiedl@fiedl-mbp ~/icecube/clsim sf/hole-ice-2018 32215a5
▶ cp -r resources/kernels/lib ~/icecube/icetray/clsim/resources/kernels/lib
```

**Comment by fiedl** [comment]
Prepare environment in zeuthen (#9):

```
[2022-09-09 16:39:46] fiedl@kepler00 ~/icecube/icetray-build
▶ /cvmfs/icecube.opensciencegrid.org/py3-v4.2.1/setup.sh
▶ module load cuda/11.6
▶ export OPENCL_VENDOR_PATH=/cvmfs/icecube.opensciencegrid.org/distrib/OpenCL_RHEL_7_x86_64/etc/OpenCL/vendors
▶ ./env-shell.sh
```

After making changes to the icetray clsim code, compile like this:

```
[2022-09-09 22:43:49] fiedl@kepler00 ~/icecube/icetray-build
▶ make
```

And then run the script:

```
[2022-09-09 22:50:44] fiedl@kepler00 ~/icecube/hole-ice-scripts
▶ scripts/propagate_photons.py
```

**Comment by fiedl** [comment]
## Merging the kernel

A simple drop in of the 2018 hole-ice code into the new propagation kernel does *not* work at this point because some of the propagation kernel has changed since 2018.

- birefringence (bfr) is new
- the layer propagation has changed

An integration of the 2018 hole-ice code could work like this:

- [x] [Replace layer propagation and bfr with a very simple pseudo propagation without considering medium boundaries](https://github.com/fiedl/hole-ice-scripts/issues/12#issuecomment-1242799501) ➝ https://github.com/icecube/icetray/commit/97577a10292226023d7435b15757cd124238c7bb
- [x] [Adopt medium-propagation algorithm from 2018 for this simple scenario](https://github.com/fiedl/hole-ice-scripts/issues/12#issuecomment-1242803708) ➝ https://github.com/icecube/icetray/commit/84323ee3ebcf40e63562fad82783325b28f42c39
- [x] [Bring back hole-ice propagation](https://github.com/fiedl/hole-ice-scripts/issues/12#issuecomment-1242806580) ➝ https://github.com/icecube/icetray/commit/32c0f47692dbd13490fa1bf73a12bf3cb990d7e8
- [ ] Bring back layer propagation
- [ ] Bring back ice tilt
- [ ] Bring back anisotropy
- [ ] Bring back bfr

**Comment by fiedl** [comment]
### Replace layer propagation with pseudo propagation

This does not consider any medium boundaries between two scatterings.

```c
// in: propagation_kernel.c.cl

floating_t sca_step_left = -my_log(RNG_CALL_UNIFORM_OC);
unsigned int layer = clamp(convert_int_sat(floatLayerForGivenZPos(photonPosAndTime.z)), 0, MEDIUM_LAYERS-1);

floating_t distancePropagated = sca_step_left * getScatteringLength(layer, photonDirAndWlen.w);
abs_lens_left -= my_divide(distancePropagated, getAbsorptionLength(layer, photonDirAndWlen.w));
if (abs_lens_left < ZERO) { abs_lens_left = ZERO; }
```

Commit: https://github.com/icecube/icetray/commit/97577a10292226023d7435b15757cd124238c7bb

Run simple propagation script:

```
fiedl@kepler00 ~/icecube/hole-ice-scripts
▶ scripts/propagate_photons.py

fiedl@fiedl-mbp ~/icecube/hole-ice-scripts
▶ steamshovel data/propagated_photons.i3
``` 

<img width="1308" alt="Bildschirmfoto 2022-09-10 um 22 22 28" src="https://user-images.githubusercontent.com/1679688/189500567-2d58238d-874e-467c-b750-12780471ce95.png">

**Comment by fiedl** [comment]
## Adopt medium-propagation algorithm from 2018

I'm adding the [medium-propagation algorithm from 2018](https://github.com/fiedl/hole-ice-scripts/issues/12#issue-1368276580) to the propagation kernel. This has no layer propagation and no hole ice, yet, and is just to make sure the code runs. This is the same dummy example [as above](https://github.com/fiedl/hole-ice-scripts/issues/12#issuecomment-1242799501) without considering medium boundaries between scatterings.

<img width="770" alt="Bildschirmfoto 2022-09-10 um 23 01 27" src="https://user-images.githubusercontent.com/1679688/189501606-f38e1e85-ac4b-4fd0-b79c-9ecc35621ea0.png">

<img width="761" alt="Bildschirmfoto 2022-09-10 um 23 01 56" src="https://user-images.githubusercontent.com/1679688/189501626-0f82803b-abee-4c61-8081-c25c3113ae85.png">

Commit: https://github.com/icecube/icetray/commit/84323ee3ebcf40e63562fad82783325b28f42c39

Run the simple propagation:

```
[2022-09-10 21:58:10] fiedl@kepler00 ~/icecube/hole-ice-scripts master ⚡ 60d7778
▶ scripts/propagate_photons.py

[2022-09-10 22:58:17] fiedl@fiedl-mbp ~/icecube/hole-ice-scripts master ⚡ 60d7778
▶ steamshovel data/propagated_photons.i3
```

<img width="1312" alt="Bildschirmfoto 2022-09-10 um 22 58 46" src="https://user-images.githubusercontent.com/1679688/189501536-47f08634-e56e-44af-82fe-e122c88e6b65.png">

Very good! That runs and the result looks pretty similar. 👍

**Comment by fiedl** [comment]
### Adding hole-ice boundaries to the medium propagation

In order to check whether the hole-ice code still works, I'm adding the hole-ice code before adding back ice layers et cetera.

The hole-ice module expects the propagation kernel to define the medium properties. The 2018 code has added this in [`I3CLSimStepToPhotonConverterOpenCL.cxx`](https://github.com/fiedl/clsim/compare/3703cb2aa42c831623bc6763bf631cbdebf7d0a2...fiedl:clsim:sf/hole-ice-2018?w=1#diff-ad445580fe59e4b0c93ee0887df9240bf81c0ed8d436524bc63925d1b5c36e34). 

I'm adding this test configuration by hand:

```c
// in: propagation_kernel.c.cl

#define HOLE_ICE
#define NUMBER_OF_CYLINDERS 1
__constant const unsigned int numberOfCylinders = 1;
__constant floating4_t cylinderPositionsAndRadii[numberOfCylinders] = {
  {-256.02301025390625, -521.2819824218750, 0, 0.4}
};
__constant floating_t cylinderScatteringLengths[numberOfCylinders] =
  {1.0};
__constant floating_t cylinderAbsorptionLengths[numberOfCylinders] =
  {0.0}; // This will make the cylinder instantly absorb the photon on entry.
```

Commit: https://github.com/icecube/icetray/commit/32c0f47692dbd13490fa1bf73a12bf3cb990d7e8

Run the test script:

```
fiedl@kepler00 ~/icecube/hole-ice-scripts
▶ scripts/propagate_photons.py

fiedl@fiedl-mbp ~/icecube/hole-ice-scripts
▶ steamshovel data/propagated_photons.i3
```

<img width="694" alt="Bildschirmfoto 2022-09-10 um 23 50 07" src="https://user-images.githubusercontent.com/1679688/189502964-4ef284d9-f766-488e-85ed-31db249676bb.png">

The image shows that the photons emitted next to the cylinder become instantly absorbed as expected from the test configuration. 👍
