### ISSUE TITLE
Configure hole ice through `I3CLSimHoleIceCylinder`

### ISSUE THREAD

**Issue by fiedl** [fiedl/hole-ice-scripts#15]
- [ ] define simulation classes
  - [x] `I3CLSimMediumCylinder` ➝ https://github.com/icecube/icetray/commit/3dc1b2c14394ee44d0497ab92db5c5aad4e431a0
  - [ ] `I3CLSimHoleIceCylinder < I3CLSimMediumCylinder`
  - [ ] `I3CLSimCableCylinder < I3CLSimMediumCylinder`
- [x] [provide example script to show how to configure it](https://github.com/fiedl/hole-ice-scripts/issues/15#issuecomment-1243044068) ➝ https://github.com/fiedl/hole-ice-scripts/commit/8023909b7800d655568c71e0b17e83bdd5c3f782
- [x] [provide steamshovel artist](https://github.com/fiedl/hole-ice-scripts/issues/15#issuecomment-1243050201) ➝ https://github.com/icecube/icetray/commit/fb44f3b5410c7f07ad393286668c98e5ab863d29
- [x] [read out cylinder configuration in clsim and pass it to the kernel](https://github.com/fiedl/hole-ice-scripts/issues/15#issuecomment-1243058314) ➝ https://github.com/icecube/icetray/commit/e7e3a4ebf802acd2dc61ef688cd10b1c7c466235

**Comment by fiedl** [comment]
My first attempt to use a `I3CLSimMediumCylinder` has failed because I did not make it serializable.

Discussion: https://icecube-spno.slack.com/archives/C02KQL9KN/p1662910414826839

Documentation: https://docs.icecube.aq/icetray/main/projects/dataio/serialization.html

**Comment by fiedl** [comment]
## Example script

I'm adding an example script that shows how to configure a hole-ice cylinder. ➝ https://github.com/fiedl/hole-ice-scripts/commit/8023909b7800d655568c71e0b17e83bdd5c3f782

```python
# in: scripts/generate_hole_ice_geometry.py

tray.Add(
  add_hole_ice_cylinders,
  Streams = [icetray.I3Frame.Geometry]
)

def add_hole_ice_cylinders(frame):
  cylinder = I3CLSimMediumCylinder()
  cylinder.x = -256.02301025390625
  cylinder.y = -521.2819824218750
  cylinder.radius = 0.3
  cylinder.scattering_length = 100.0
  cylinder.absorption_length = 0.0

  cylinders = I3CLSimMediumCylinderSeries([cylinder])
  frame.Put("I3CLSimMediumCylinders", cylinders)
```

```
[2022-09-11 23:01:53] fiedl@kepler00 ~/icecube/hole-ice-scripts master ⚡ 60d7778
▶ scripts/generate_hole_ice_geometry.py
```

**Comment by fiedl** [comment]
## Steamshovel artist

I'm providing a basic steamshovel artist to render the medium cylinders. ➝ https://github.com/icecube/icetray/commit/fb44f3b5410c7f07ad393286668c98e5ab863d29

```
[2022-09-11 23:01:53] fiedl@kepler00 ~/icecube/hole-ice-scripts master
▶ scripts/generate_photons.py
▶ scripts/generate_hole_ice_geometry.py
▶ scripts/propagate_photons.py

[2022-09-11 23:49:21] fiedl@fiedl-mbp ~/icecube/hole-ice-scripts master ⚡ e24717d
▶ steamshovel data/propagated_photons.i3
```

<img width="1307" alt="Bildschirmfoto 2022-09-11 um 23 50 18" src="https://user-images.githubusercontent.com/1679688/189550402-297839bd-3424-4001-ba70-77c675113c9f.png">

**Comment by fiedl** [comment]
## Extract the `I3CLSimMediumCylinderSeries` in clsim

I need to extract the cylinder information from the frame and pass it them down to the kernel. ➝ https://github.com/icecube/icetray/commit/e7e3a4ebf802acd2dc61ef688cd10b1c7c466235

Before the server-client rewrite of clsim, I've extracted the parameters in the `I3CLSimModule`.

![Bildschirmfoto 2022-09-13 um 01 54 36](https://user-images.githubusercontent.com/1679688/189778508-6a139cc2-4b7a-406f-8d5f-b0f8f7bebba6.png)

Code from 2018: https://github.com/fiedl/clsim/compare/3703cb2aa42c831623bc6763bf631cbdebf7d0a2...fiedl:clsim:sf/hole-ice-2018?w=1

But now, the `I3CLSimModule` appears to be dead code.

Maybe this is done in `common.py` now, and passed to `I3CLSimModuleHelper::initializeOpenCL`.

Discussion: https://icecube-spno.slack.com/archives/D02ST977K6F/p1662936099850589

The information is passed from `common.py` to `I3CLSimModuleHelper::initializeOpenCL`, from there to the `I3CLSimStepToPhotonConverterOpenCL`, which compiles it into the kernel.

Commit: https://github.com/icecube/icetray/commit/e7e3a4ebf802acd2dc61ef688cd10b1c7c466235

Run the test script:

```
[2022-09-13 01:45:28] fiedl@kepler00 ~/icecube/hole-ice-scripts master ⚡ e24717d
▶ scripts/generate_photons.py
▶ scripts/generate_hole_ice_geometry.py
▶ scripts/propagate_photons.py

[2022-09-13 01:46:32] fiedl@fiedl-mbp ~/icecube/hole-ice-scripts master ⚡ e24717d
▶ steamshovel data/propagated_photons.i3
```

![Bildschirmfoto 2022-09-13 um 01 48 24](https://user-images.githubusercontent.com/1679688/189778180-b4d7259e-c294-4595-97b6-c98fc645c7a5.png)

**Comment by fiedl** [comment]
### I3CLSimModuleHelper::initializeOpenCL

Passing down the configuration, I need to pass one more parameter to `I3CLSimModuleHelper::initializeOpenCL`, increasing the number of parameters from 15 to 16.

However, boost python has a limit of 15 parameters per default. One can increase this limit with `#define BOOST_PYTHON_MAX_ARITY 20`.

The original definition is in `/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/include/boost/python/detail/preprocessor.hpp`: `#define BOOST_PYTHON_MAX_ARITY 15`

Documentation: https://www.boost.org/doc/libs/1_41_0/libs/python/doc/v2/configuration.html

#### Discussion

Previous Discussion (2020):
https://icecube-spno.slack.com/archives/C02KQL9KN/p1587418792173700

Previous Issue:
https://github.com/fiedl/hole-ice-study/issues/121

Previous Discussion (2014):
https://github.com/fiedl/clsim/commit/e7bfe2da57215532479e8a362effe48474219d88

First Discussion (2014):
https://github.com/fiedl/clsim/commit/9c7f0e4ab90713e0ee41cda262b536e2ad67723a#commitcomment-6518341

Summary: https://github.com/fiedl/hole-ice-study/issues/121#issuecomment-617239528

> From our [slack discussion](https://icecube-spno.slack.com/archives/C02KQL9KN/p1587418792173700):
> 
> - If we really need `#define BOOST_PYTHON_MAX_ARITY`, this should be done in https://github.com/IceCube-SPNO/IceTrayCombo/blob/master/cmake/tool-patches/common/pybindings.hpp, which gets included in all pybindings targets. To modify the master-control header https://github.com/IceCube-SPNO/IceTrayCombo/blob/master/cmake/I3.h.in is discouraged.
> - We should find an alternative to increasing the signature maximum. Increasing this number would also increase the number of required pre-processor slowing down compilation.
> - The options struct is a good idea.
> - Defining a boost-python setter for
> 
>   ```cpp
>   struct OpenCLInitOptions {
>     const I3CLSimOpenCLDevice &device;
>   }
>   ```
> 
>   would mean that one would want to set a constant reference.
> 
>   > here you’re trying to assign to a const reference, which is a thing you cannot do, because assignment invokes the operator= of there referenced object in c++, and there is no const operator=
> 
> - a `shared_ptr` to the `device` would work 
> 
> I also was thinking about leaving `device` a const reference separate from the options struct. This depends on how the python code uses the `device`.


#### Further work

- [x] Increase the limit for now ➝ https://github.com/icecube/icetray/commit/962e9f494b8d5f2bc013ecbc1bc096d34f120467
- [ ] Later: Migrate to options struct

#### Increasing the limit

- [x] `#define BOOST_PYTHON_MAX_ARITY 16` in `cmake/tool-patches/common/pybindings.hpp` does not help because this is included after `boost/python.hpp`. 👎 
- [x] `#define BOOST_PYTHON_MAX_ARITY 16` in `cmake/I3.h.in` does resolve the issue 👍  but is discouraged, thus should be removed before pull request (instead migrate to options struct) ➝ https://github.com/icecube/icetray/commit/962e9f494b8d5f2bc013ecbc1bc096d34f120467
